Updated start.py to generate config using the correct user ID (fixes #16824, #15202)
