Fix type annotation for `visited_chains` after `mypy` upgrade.